---
title: "betas_take_two"
output: html_document
date: "2024-04-17"
---
plink is the new baseline, plotting new tools against plink. filtering by significance (blue line in manplots) so it's not all million

```{r}
library(data.table)
library(dplyr)
library(ggplot2)
#filtering down plink; using suggestive line from manplot fn at 1e-5
plinkqt<-fread('/home/wprice2/gwas_results/5000continuous.TRAIT.glm.linear')
plinkcc<-fread('/home/wprice2/gwas_results/5000categorical.TRAIT.glm.logistic.hybrid')
plinkqt<-filter(plinkqt,P<=1e-5)
plinkcc<-filter(plinkcc,P<=1e-5)
plinkcc<-mutate(plinkcc,BETA=log(OR))
```

```{r}
#regenie continuous
reg<-fread('/home/igregga/regenie-out/5000continuous-test_TRAIT.regenie')
merged<-left_join(plinkqt,reg,by=c('ID'='ID'))
r2 <- (cor(merged$BETA.x, merged$BETA.y, method='pearson'))^2
r2 <- as.character(round(r2, digits=2))
ggplot(merged,aes(x=BETA.x,y=BETA.y))+
  geom_point()+
  geom_smooth(method='lm')+
  theme_gray(base_size=18)+
  geom_text(x=-60,y=40,label=paste('R2=',r2),color='blue',size=6)
```
```{r}
#regenie categorical
reg<-fread('/home/igregga/regenie-out/5000categorical-test_TRAIT.regenie')
merged<-left_join(plinkcc,reg,by=c('ID'='ID'))
r2 <- (cor(merged$BETA.x, merged$BETA.y, method='pearson'))^2
r2 <- as.character(round(r2, digits=2))
ggplot(merged,aes(x=BETA.x,y=BETA.y))+geom_point()+geom_smooth(method='lm')+theme_gray(base_size=18)+geom_text(x=-.75,y=.75,label=paste('R2=',r2),color='blue',size=6)
```
```{r}
#bolt continuous
bolt<-fread('/home/tfischer1/LMM_for_large_GWAS/BOLT_results/5000simu-genos_qt_stats.tab')
merged<-left_join(plinkqt,bolt,by=c('ID'='SNP'))
r2 <- (cor(merged$BETA.x, merged$BETA.y, method='pearson'))^2
r2 <- as.character(round(r2, digits=2))
ggplot(merged,aes(x=BETA.x,y=BETA.y))+geom_point()+geom_smooth(method='lm')+theme_gray(base_size=18)+geom_text(x=-60,y=40,label=paste('R2=',r2),color='blue',size=6)
```
```{r}
#bolt categorical
bolt<-fread('/home/tfischer1/LMM_for_large_GWAS/BOLT_results/5000simu-genos_cc_stats.tab')
merged<-left_join(plinkcc,bolt,by=c('ID'='SNP'))
r2 <- (cor(merged$BETA.x, merged$BETA.y, method='pearson'))^2
r2 <- as.character(round(r2, digits=2))
ggplot(merged,aes(x=BETA.x,y=BETA.y))+geom_point()+geom_smooth(method='lm')+theme_gray(base_size=18)+geom_text(x=-.75,y=.1,label=paste('R2=',r2),color='blue',size=6)
```
```{r}
#saige continuous
saige<-fread('/home/tfischer1/LMM_for_large_GWAS/SAIGE_results/5000_qt_fullGRM_with_vr.txt')
merged<-left_join(plinkqt,saige,by=c('ID'='MarkerID'))
r2 <- (cor(merged$BETA.x, merged$BETA.y, method='pearson'))^2
r2 <- as.character(round(r2, digits=2))
ggplot(merged,aes(x=BETA.x,y=BETA.y))+geom_point()+geom_smooth(method='lm')+theme_gray(base_size=18)+geom_text(x=-60,y=.2,label=paste('R2=',r2),color='blue',size=6)
```
```{r}
#saige categorical
saige<-fread('/home/tfischer1/LMM_for_large_GWAS/SAIGE_results/5000_cc_fullGRM_with_vr.txt')
merged<-left_join(plinkcc,saige,by=c('ID'='MarkerID'))
r2 <- (cor(merged$BETA.x, merged$BETA.y, method='pearson'))^2
r2 <- as.character(round(r2, digits=2))
ggplot(merged,aes(x=BETA.x,y=BETA.y))+geom_point()+geom_smooth(method='lm')+theme_gray(base_size=18)+geom_text(x=-.75,y=.5,label=paste('R2=',r2),color='blue',size=6)
```
