---
title: "manplots_fancier"
output: html_document
date: "2024-04-17"
---
because a markdown is better for saving plots
```{r}
library(data.table)
library(qqman)
library(dplyr)

#get the three sig plink snps from qt
plinkqt<-fread('/home/wprice2/gwas_results/5000continuous.TRAIT.glm.linear')
hits<-filter(plinkqt,P<=5e-8)
hits<-arrange(hits,P)
sigsnps<-pull(hits,ID)

manhattan(plinkqt,chr='#CHROM',bp='POS',snp='ID',highlight=sigsnps)

```

```{r}
#bolt
boltqt<-fread('/home/tfischer1/LMM_for_large_GWAS/BOLT_results/5000simu-genos_qt_stats.tab')
manhattan(boltqt,p='P_BOLT_LMM_INF',highlight=sigsnps)
```

```{r}
#saige
saigeqt<-fread('/home/tfischer1/LMM_for_large_GWAS/SAIGE_results/5000_qt_fullGRM_with_vr.txt')
manhattan(saigeqt,bp='POS',p='p.value',snp='MarkerID',highlight=sigsnps)
```

```{r}
#regenie
regqt<-fread('/home/igregga/regenie-out/5000continuous-test_TRAIT.regenie')
manhattan(regqt,snp='ID',chr='CHROM',bp='GENPOS',p='LOG10P',logp=F,highlight=sigsnps)
```

```{r}
#checking the top hits in the real betas
real<-fread('/home/igregga/LMM_files/phenos/simu-qt-h2_0.2_filtered.par')
realhits<-filter(real,QTL%in%sigsnps)
realhits
#uh oh
#realhits<-left_join(hits,real,by=c('QTL'='ID'))
#realhits
#can't join, not present in the data UH OHHHH
real2<-fread('/home/data/simulated_gwas/simu-qt-h2_0.2.par')
realhits<-filter(real2,QTL%in%sigsnps)
realhits
```